### ISSUE TITLE
Bot does not re-join voice channel

### ISSUE THREAD

**Issue by red-gum-tree** [Flosi23/rythm#1]
After the queue clears and bot automatically leaves the voice channel, bot is unable to re-join the voice channel with a !play command. The queue continues to fill like normal.

**Comment by simonwkla** [comment]
Oh ok. I will look into this as soon as possible. I will also try to make a documentation on how to host the bot but it seems like you got it to run without any help. Congrats

**Comment by simonwkla** [comment]
Issue is fixed now by changing the bots behaviour. The bot now longer leaves the vc when its Idle and the queue is empty.

**Comment by red-gum-tree** [comment]
Thank you for your quick response, I wish I could propose changes but I am
new to TS.
